In [11]:
import numpy as np
import pandas as pd

In [12]:
#uzeto iz fajla za analizu podataka
kolone = ["ID", "Age", "Gender", "Education", "Country", "Ethnicity", 
            "Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsiveness", "SS", 
            "Alchocol", "Amphet", "Amyl", "Benzos", "Caff", "Canabis", "Choc", "Coke", "Crack", "Ecstasy", 
            "Heroin", "Ketamin", "LegalH", "LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA"]

podaci = pd.read_csv('drug_consumption.data', names = kolone)

podaci = podaci.drop('ID', axis = 1)
podaci 

Age   Gender  Education  Country  Ethnicity   Nscore   Escore  \
0     0.49788  0.48246   -0.05921  0.96082    0.12600  0.31287 -0.57545   
1    -0.07854 -0.48246    1.98437  0.96082   -0.31685 -0.67825  1.93886   
2     0.49788 -0.48246   -0.05921  0.96082   -0.31685 -0.46725  0.80523   
3    -0.95197  0.48246    1.16365  0.96082   -0.31685 -0.14882 -0.80615   
4     0.49788  0.48246    1.98437  0.96082   -0.31685  0.73545 -1.63340   
...       ...      ...        ...      ...        ...      ...      ...   
1880 -0.95197  0.48246   -0.61113 -0.57009   -0.31685 -1.19430  1.74091   
1881 -0.95197 -0.48246   -0.61113 -0.57009   -0.31685 -0.24649  1.74091   
1882 -0.07854  0.48246    0.45468 -0.57009   -0.31685  1.13281 -1.37639   
1883 -0.95197  0.48246   -0.61113 -0.57009   -0.31685  0.91093 -1.92173   
1884 -0.95197 -0.48246   -0.61113  0.21128   -0.31685 -0.46725  2.12700   

       Oscore   Ascore   Cscore  ...  Ecstasy  Heroin Ketamin LegalH  LSD  \
0    -0.58331 -0.91699 -0.00665  ...      CL0     CL0     CL0    CL0  CL0   
1     1.43533  0.76096 -0.14277  ...      CL4     CL0     CL2    CL0  CL2   
2    -0.84732 -1.62090 -1.01450  ...      CL0     CL0     CL0    CL0  CL0   
3    -0.01928  0.59042  0.58489  ...      CL0     CL0     CL2    CL0  CL0   
4    -0.45174 -0.30172  1.30612  ...      CL1     CL0     CL0    CL1  CL0   
...       ...      ...      ...  ...      ...     ...     ...    ...  ...   
1880  1.88511  0.76096 -1.13788  ...      CL0     CL0     CL0    CL3  CL3   
1881  0.58331  0.76096 -1.51840  ...      CL2     CL0     CL0    CL3  CL5   
1882 -1.27553 -1.77200 -1.38502  ...      CL4     CL0     CL2    CL0  CL2   
1883  0.29338 -1.62090 -2.57309  ...      CL3     CL0     CL0    CL3  CL3   
1884  1.65653  1.11406  0.41594  ...      CL3     CL0     CL0    CL3  CL3   

     Meth Mushrooms Nicotine Semer  VSA  
0     CL0       CL0      CL2   CL0  CL0  
1     CL3       CL0      CL4   CL0  CL0  
2     CL0       CL1      CL0   CL0  CL0  
3     CL0       CL0      CL2   CL0  CL0  
4     CL0       CL2      CL2   CL0  CL0  
...   ...       ...      ...   ...  ...  
1880  CL0       CL0      CL0   CL0  CL5  
1881  CL4       CL4      CL5   CL0  CL0  
1882  CL0       CL2      CL6   CL0  CL0  
1883  CL0       CL3      CL4   CL0  CL0  
1884  CL0       CL3      CL6   CL0  CL2  

[1885 rows x 31 columns]

In [13]:
klase = []
atributi = []
for x in podaci.columns:
    if x == 'Alchocol':
        break
    atributi.append(x)
print(atributi)

for x in podaci.columns:
    if x not in atributi:
        klase.append(x)
print(klase)

['Age', 'Gender', 'Education', 'Country', 'Ethnicity', 'Nscore', 'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsiveness', 'SS']
['Alchocol', 'Amphet', 'Amyl', 'Benzos', 'Caff', 'Canabis', 'Choc', 'Coke', 'Crack', 'Ecstasy', 'Heroin', 'Ketamin', 'LegalH', 'LSD', 'Meth', 'Mushrooms', 'Nicotine', 'Semer', 'VSA']


In [14]:
#podesavanje podataka malo
for x in klase:
    a = podaci[x].unique()
    a.sort()
    print(a)

['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4']
['CL0' 'CL1' 'CL2' 'CL3' 'CL4' 'CL5' 'CL6']


In [25]:
podaci_skalirano = podaci.copy()

opisni_niz1 = podaci['Alchocol'].unique()
opisni_niz1.sort()
n = len(podaci_skalirano['Heroin'])
    
for x in klase:
    for i in range(n):
        podaci_skalirano[x][i] = int(podaci_skalirano[x][i].strip('CL'))
    print(podaci_skalirano[x].unique())

podaci_skalirano
#podaci_skalirano['Alchocol'].unique()

/tmp/ipykernel_5161/3803795111.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  podaci_skalirano[x][i] = int(podaci_skalirano[x][i].strip('CL'))


[5 6 4 2 1 0 3]
[2 0 1 3 5 4 6]
[0 2 1 3 5 4 6]
[2 0 3 1 4 5 6]
[6 5 4 3 0 1 2]
[0 4 3 2 1 6 5]
[5 6 4 0 3 2 1]
[0 3 2 1 6 5 4]
[0 1 2 3 5 4 6]
[0 4 1 3 2 6 5]
[0 1 2 3 5 6 4]
[0 2 3 1 5 4 6]
[0 1 2 3 5 4 6]
[0 2 1 3 4 5 6]
[0 3 1 6 4 2 5]
[0 1 2 3 4 5 6]
[2 4 0 6 1 3 5]
[0 2 3 4 1]
[0 1 3 6 2 5 4]


Age   Gender  Education  Country  Ethnicity   Nscore   Escore  \
0     0.49788  0.48246   -0.05921  0.96082    0.12600  0.31287 -0.57545   
1    -0.07854 -0.48246    1.98437  0.96082   -0.31685 -0.67825  1.93886   
2     0.49788 -0.48246   -0.05921  0.96082   -0.31685 -0.46725  0.80523   
3    -0.95197  0.48246    1.16365  0.96082   -0.31685 -0.14882 -0.80615   
4     0.49788  0.48246    1.98437  0.96082   -0.31685  0.73545 -1.63340   
...       ...      ...        ...      ...        ...      ...      ...   
1880 -0.95197  0.48246   -0.61113 -0.57009   -0.31685 -1.19430  1.74091   
1881 -0.95197 -0.48246   -0.61113 -0.57009   -0.31685 -0.24649  1.74091   
1882 -0.07854  0.48246    0.45468 -0.57009   -0.31685  1.13281 -1.37639   
1883 -0.95197  0.48246   -0.61113 -0.57009   -0.31685  0.91093 -1.92173   
1884 -0.95197 -0.48246   -0.61113  0.21128   -0.31685 -0.46725  2.12700   

       Oscore   Ascore   Cscore  ...  Ecstasy  Heroin Ketamin LegalH LSD Meth  \
0    -0.58331 -0.91699 -0.00665  ...        0       0       0      0   0    0   
1     1.43533  0.76096 -0.14277  ...        4       0       2      0   2    3   
2    -0.84732 -1.62090 -1.01450  ...        0       0       0      0   0    0   
3    -0.01928  0.59042  0.58489  ...        0       0       2      0   0    0   
4    -0.45174 -0.30172  1.30612  ...        1       0       0      1   0    0   
...       ...      ...      ...  ...      ...     ...     ...    ...  ..  ...   
1880  1.88511  0.76096 -1.13788  ...        0       0       0      3   3    0   
1881  0.58331  0.76096 -1.51840  ...        2       0       0      3   5    4   
1882 -1.27553 -1.77200 -1.38502  ...        4       0       2      0   2    0   
1883  0.29338 -1.62090 -2.57309  ...        3       0       0      3   3    0   
1884  1.65653  1.11406  0.41594  ...        3       0       0      3   3    0   

     Mushrooms Nicotine Semer VSA  
0            0        2     0   0  
1            0        4     0   0  
2            1        0     0   0  
3            0        2     0   0  
4            2        2     0   0  
...        ...      ...   ...  ..  
1880         0        0     0   5  
1881         4        5     0   0  
1882         2        6     0   0  
1883         3        4     0   0  
1884         3        6     0   2  

[1885 rows x 31 columns]

In [17]:
for x in klase:
    podaci_skalirano[x] = podaci_skalirano[x].astype('float64')
    
podaci_skalirano.dtypes

Age              float64
Gender           float64
Education        float64
Country          float64
Ethnicity        float64
Nscore           float64
Escore           float64
Oscore           float64
Ascore           float64
Cscore           float64
Impulsiveness    float64
SS               float64
Alchocol         float64
Amphet           float64
Amyl             float64
Benzos           float64
Caff             float64
Canabis          float64
Choc             float64
Coke             float64
Crack            float64
Ecstasy          float64
Heroin           float64
Ketamin          float64
LegalH           float64
LSD              float64
Meth             float64
Mushrooms        float64
Nicotine         float64
Semer            float64
VSA              float64
dtype: object

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [19]:
klasa = podaci_skalirano['Alchocol']
podaci_bez_klase = podaci_skalirano.drop('Alchocol', axis = 1)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(podaci_bez_klase, klasa, test_size= 0.30, stratify= klasa, random_state= 42)

In [21]:
drvo_klasifikacije = DecisionTreeClassifier()
drvo_klasifikacije.fit(X_train, y_train)

DecisionTreeClassifier()

In [22]:
from sklearn.metrics import classification_report
from termcolor import colored, cprint
def report(model, x, y, text = "trening", ):
    y_pred = model.predict(x)
    
    print(colored('\t' + f'Klasifikacioni izveštaj za model {type(model).__name__} nad {text} podacima', 'blue', attrs= ['bold']))
    cprint('----------------------------------------------------------------------------------------------', attrs= ['bold'])
    cprint(classification_report(y, y_pred), attrs= ['dark']) 
    cprint('----------------------------------------------------------------------------------------------', attrs= ['bold'])

In [23]:
report(drvo_klasifikacije, X_test, y_test, text= 'test')

	Klasifikacioni izveštaj za model DecisionTreeClassifier nad test podacima
----------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

         0.0       0.20      0.20      0.20        10
         1.0       0.10      0.10      0.10        10
         2.0       0.14      0.15      0.15        20
         3.0       0.12      0.13      0.13        60
         4.0       0.17      0.19      0.18        86
         5.0       0.42      0.38      0.40       228
         6.0       0.27      0.28      0.28       152

    accuracy                           0.28       566
   macro avg       0.20      0.20      0.20       566
weighted avg       0.29      0.28      0.29       566

----------------------------------------------------------------------------------------------
